### ISSUE TITLE
Cant find way to login

### ISSUE THREAD

**Issue by maco144** [delay/feathers-vue-blog-admin-demo#1]
Running as client creating an account works but there seems to be no way to login. I have ran the npm install commands in server. I realize I'm not giving much to troubleshoot with here (im a beginner) but as is I cannot get logged in.

**Comment by delay** [comment]
Do you see the signup and login screen?  If so, can you signup? Then use that account to login...  If it doesn't allow you to signup then my guess would be the server side portion is not actually running to receive your signup/login input.

**Comment by delay** [comment]
Also to check whether server side is running. http://localhost:3030/ does that show you a webpage about feathers?

**Comment by maco144** [comment]
I had the server running and was getting the confirmation of the account created - yet after I couldnt login. I was trying to reproduce today and everything worked. I am not sure what changed but the issue for me is closed at this point.
